package ca.yorku.eecs3311.model.user;

import ca.yorku.eecs3311.model.enums.AccountStatus;
import ca.yorku.eecs3311.model.enums.UserType;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Test suite for Faculty user type.
 */
public class FacultyManualTest {

    private Faculty faculty;

    @BeforeEach
    public void setUp() {
        faculty = new Faculty("professor@york.edu", "SecurePass123!", "Computer Science",
                "FAC1001", "Full Professor");
    }

    // ============ CONSTRUCTOR TESTS ============

    @Test
    @DisplayName("should create Faculty with correct properties")
    public void testFacultyConstructor() {
        assertEquals("professor@york.edu", faculty.getEmail());
        assertEquals("FAC1001", faculty.getFacultyID());
        assertEquals("Full Professor", faculty.getPosition());
        assertEquals(UserType.FACULTY, faculty.getUserType());
        assertEquals(AccountStatus.PENDING, faculty.getAccountStatus());
    }

    @Test
    @DisplayName("should auto-generate userId on construction")
    public void testAutoGeneratedUserId() {
        assertNotNull(faculty.getUserId());
        assertFalse(faculty.getUserId().isEmpty());
    }

    // ============ CREDENTIAL AND HOURLY RATE TESTS ============

    @Test
    @DisplayName("should return correct credential number (Faculty ID)")
    public void testGetCredentialNumber() {
        assertEquals("FAC1001", faculty.getCredentialNumber());
    }

    @Test
    @DisplayName("should return correct hourly rate for Faculty (10.00)")
    public void testGetHourlyRate() {
        assertEquals(10.00, faculty.getHourlyRate());
    }

    @Test
    @DisplayName("should have higher hourly rate than Student")
    public void testFacultyHigherHourlyRate() {
        Student student = new Student("s@york.edu", "Pass123!", "CS", "S001", "EECS", 1);
        assertTrue(faculty.getHourlyRate() > student.getHourlyRate());
    }

    // ============ GETTERS AND SETTERS TESTS ============

    @Test
    @DisplayName("should get and set Faculty ID")
    public void testGetSetFacultyID() {
        faculty.setFacultyID("FAC2001");
        assertEquals("FAC2001", faculty.getFacultyID());
        assertEquals("FAC2001", faculty.getCredentialNumber());
    }

    @Test
    @DisplayName("should get and set Position")
    public void testGetSetPosition() {
        faculty.setPosition("Associate Professor");
        assertEquals("Associate Professor", faculty.getPosition());
    }

    @Test
    @DisplayName("should handle various position titles")
    public void testVariousPositions() {
        String[] positions = {"Assistant Professor", "Associate Professor", "Full Professor", "Lecturer", "Adjunct"};
        for (String position : positions) {
            faculty.setPosition(position);
            assertEquals(position, faculty.getPosition());
        }
    }

    @Test
    @DisplayName("should get and set Email")
    public void testGetSetEmail() {
        faculty.setEmail("newprof@york.edu");
        assertEquals("newprof@york.edu", faculty.getEmail());
    }

    @Test
    @DisplayName("should get and set Department")
    public void testGetSetDepartment() {
        faculty.setDepartment("Electrical Engineering");
        assertEquals("Electrical Engineering", faculty.getDepartment());
    }

    // ============ ACCOUNT STATUS TESTS ============

    @Test
    @DisplayName("should activate Faculty account")
    public void testActivateAccount() {
        faculty.activate();
        assertEquals(AccountStatus.ACTIVE, faculty.getAccountStatus());
        assertTrue(faculty.isActive());
    }

    @Test
    @DisplayName("should suspend Faculty account")
    public void testSuspendAccount() {
        faculty.suspend();
        assertEquals(AccountStatus.SUSPENDED, faculty.getAccountStatus());
        assertFalse(faculty.isActive());
    }

    @Test
    @DisplayName("should deactivate Faculty account")
    public void testDeactivateAccount() {
        faculty.deactivate();
        assertEquals(AccountStatus.DEACTIVATED, faculty.getAccountStatus());
    }

    // ============ CREDENTIAL VALIDATION TESTS ============

    @Test
    @DisplayName("should validate correct credentials")
    public void testValidateCredentialsCorrect() {
        assertTrue(faculty.validateCredentials("professor@york.edu", "SecurePass123!"));
    }

    @Test
    @DisplayName("should reject incorrect password")
    public void testValidateCredentialsIncorrectPassword() {
        assertFalse(faculty.validateCredentials("professor@york.edu", "WrongPass123!"));
    }

    @Test
    @DisplayName("should reject incorrect email")
    public void testValidateCredentialsIncorrectEmail() {
        assertFalse(faculty.validateCredentials("wrong@york.edu", "SecurePass123!"));
    }

    // ============ PROFILE UPDATE TESTS ============

    @Test
    @DisplayName("should update profile email and department")
    public void testUpdateProfile() {
        faculty.updateProfile("newprof@york.edu", "Electrical Engineering");
        assertEquals("newprof@york.edu", faculty.getEmail());
        assertEquals("Electrical Engineering", faculty.getDepartment());
    }

    // ============ CSV CONSTRUCTOR TESTS ============

    @Test
    @DisplayName("should construct Faculty from CSV")
    public void testCSVConstructor() {
        LocalDateTime regDate = LocalDateTime.now().minusDays(10);
        Faculty csvFaculty = new Faculty("fac-uuid-123", "professor@york.edu", "Pass123!",
                AccountStatus.ACTIVE, regDate, "Computer Science",
                "FAC1001", "Full Professor");

        assertEquals("fac-uuid-123", csvFaculty.getUserId());
        assertEquals("FAC1001", csvFaculty.getFacultyID());
        assertEquals("Full Professor", csvFaculty.getPosition());
        assertEquals(AccountStatus.ACTIVE, csvFaculty.getAccountStatus());
    }

    // ============ STRING REPRESENTATION TESTS ============

    @Test
    @DisplayName("should generate meaningful toString representation")
    public void testToString() {
        String str = faculty.toString();
        assertNotNull(str);
        assertTrue(str.contains("Faculty"));
        assertTrue(str.contains("FAC1001"));
    }

    // ============ MULTIPLE FACULTY TESTS ============

    @Test
    @DisplayName("should create multiple faculty with different IDs")
    public void testMultipleFacultyHaveUniqueIds() {
        Faculty faculty2 = new Faculty("prof2@york.edu", "Pass123!", "Physics",
                "FAC2001", "Associate Professor");
        assertNotEquals(faculty.getUserId(), faculty2.getUserId());
    }

    // ============ EDGE CASE TESTS ============

    @Test
    @DisplayName("should handle empty position")
    public void testEmptyPosition() {
        faculty.setPosition("");
        assertEquals("", faculty.getPosition());
    }

    @Test
    @DisplayName("should handle empty Faculty ID")
    public void testEmptyFacultyID() {
        faculty.setFacultyID("");
        assertEquals("", faculty.getFacultyID());
    }
}
