package ca.yorku.eecs3311.model.user;

import ca.yorku.eecs3311.model.enums.AccountStatus;
import ca.yorku.eecs3311.model.enums.UserType;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Test suite for Guest user type.
 */
public class GuestManualTest {

    private Guest guest;

    @BeforeEach
    public void setUp() {
        guest = new Guest("guest@external.com", "SecurePass123!", "Engineering",
                "GUEST1001", "Tech Corporation", "sponsor@techcorp.com");
    }

    // ============ CONSTRUCTOR TESTS ============

    @Test
    @DisplayName("should create Guest with correct properties")
    public void testGuestConstructor() {
        assertEquals("guest@external.com", guest.getEmail());
        assertEquals("GUEST1001", guest.getGuestID());
        assertEquals("Tech Corporation", guest.getOrganization());
        assertEquals("sponsor@techcorp.com", guest.getSponsorEmail());
        assertEquals(UserType.GUEST, guest.getUserType());
        assertEquals(AccountStatus.PENDING, guest.getAccountStatus());
    }

    @Test
    @DisplayName("should auto-generate userId on construction")
    public void testAutoGeneratedUserId() {
        assertNotNull(guest.getUserId());
        assertFalse(guest.getUserId().isEmpty());
    }

    // ============ CREDENTIAL AND HOURLY RATE TESTS ============

    @Test
    @DisplayName("should return correct credential number (Guest ID)")
    public void testGetCredentialNumber() {
        assertEquals("GUEST1001", guest.getCredentialNumber());
    }

    @Test
    @DisplayName("should return highest hourly rate (15.00)")
    public void testGetHourlyRate() {
        assertEquals(15.00, guest.getHourlyRate());
    }

    @Test
    @DisplayName("should have highest hourly rate among all user types")
    public void testGuestHighestHourlyRate() {
        Student student = new Student("s@york.edu", "Pass123!", "CS", "S001", "EECS", 1);
        Researcher researcher = new Researcher("r@york.edu", "Pass123!", "CS", "R001", "ML", "G001");
        Faculty faculty = new Faculty("f@york.edu", "Pass123!", "CS", "F001", "Prof");

        assertTrue(guest.getHourlyRate() > student.getHourlyRate());
        assertTrue(guest.getHourlyRate() > researcher.getHourlyRate());
        assertTrue(guest.getHourlyRate() > faculty.getHourlyRate());
    }

    // ============ GETTERS AND SETTERS TESTS ============

    @Test
    @DisplayName("should get and set Guest ID")
    public void testGetSetGuestID() {
        guest.setGuestID("GUEST2001");
        assertEquals("GUEST2001", guest.getGuestID());
        assertEquals("GUEST2001", guest.getCredentialNumber());
    }

    @Test
    @DisplayName("should get and set Organization")
    public void testGetSetOrganization() {
        guest.setOrganization("Innovation Labs Inc");
        assertEquals("Innovation Labs Inc", guest.getOrganization());
    }

    @Test
    @DisplayName("should get and set Sponsor Email")
    public void testGetSetSponsorEmail() {
        guest.setSponsorEmail("newsponsor@company.com");
        assertEquals("newsponsor@company.com", guest.getSponsorEmail());
    }

    @Test
    @DisplayName("should get and set Email")
    public void testGetSetEmail() {
        guest.setEmail("newguest@external.com");
        assertEquals("newguest@external.com", guest.getEmail());
    }

    @Test
    @DisplayName("should get and set Department")
    public void testGetSetDepartment() {
        guest.setDepartment("Computer Science");
        assertEquals("Computer Science", guest.getDepartment());
    }

    // ============ ACCOUNT STATUS TESTS ============

    @Test
    @DisplayName("should activate Guest account")
    public void testActivateAccount() {
        guest.activate();
        assertEquals(AccountStatus.ACTIVE, guest.getAccountStatus());
        assertTrue(guest.isActive());
    }

    @Test
    @DisplayName("should suspend Guest account")
    public void testSuspendAccount() {
        guest.suspend();
        assertEquals(AccountStatus.SUSPENDED, guest.getAccountStatus());
        assertFalse(guest.isActive());
    }

    @Test
    @DisplayName("should deactivate Guest account")
    public void testDeactivateAccount() {
        guest.deactivate();
        assertEquals(AccountStatus.DEACTIVATED, guest.getAccountStatus());
    }

    // ============ CREDENTIAL VALIDATION TESTS ============

    @Test
    @DisplayName("should validate correct credentials")
    public void testValidateCredentialsCorrect() {
        assertTrue(guest.validateCredentials("guest@external.com", "SecurePass123!"));
    }

    @Test
    @DisplayName("should reject incorrect password")
    public void testValidateCredentialsIncorrectPassword() {
        assertFalse(guest.validateCredentials("guest@external.com", "WrongPass123!"));
    }

    @Test
    @DisplayName("should reject incorrect email")
    public void testValidateCredentialsIncorrectEmail() {
        assertFalse(guest.validateCredentials("wrong@external.com", "SecurePass123!"));
    }

    // ============ PROFILE UPDATE TESTS ============

    @Test
    @DisplayName("should update profile email and department")
    public void testUpdateProfile() {
        guest.updateProfile("newguest@external.com", "Computer Science");
        assertEquals("newguest@external.com", guest.getEmail());
        assertEquals("Computer Science", guest.getDepartment());
    }

    @Test
    @DisplayName("should not update sponsor info via updateProfile")
    public void testUpdateProfileDoesNotAffectSponsor() {
        String originalOrg = guest.getOrganization();
        String originalSponsor = guest.getSponsorEmail();
        guest.updateProfile("newguest@external.com", "New Dept");
        assertEquals(originalOrg, guest.getOrganization());
        assertEquals(originalSponsor, guest.getSponsorEmail());
    }

    // ============ CSV CONSTRUCTOR TESTS ============

    @Test
    @DisplayName("should construct Guest from CSV")
    public void testCSVConstructor() {
        LocalDateTime regDate = LocalDateTime.now().minusDays(20);
        Guest csvGuest = new Guest("guest-uuid-123", "guest@external.com", "Pass123!",
                AccountStatus.ACTIVE, regDate, "Engineering",
                "GUEST1001", "Tech Corp", "sponsor@techcorp.com");

        assertEquals("guest-uuid-123", csvGuest.getUserId());
        assertEquals("GUEST1001", csvGuest.getGuestID());
        assertEquals("Tech Corp", csvGuest.getOrganization());
        assertEquals("sponsor@techcorp.com", csvGuest.getSponsorEmail());
        assertEquals(AccountStatus.ACTIVE, csvGuest.getAccountStatus());
    }

    // ============ STRING REPRESENTATION TESTS ============

    @Test
    @DisplayName("should generate meaningful toString representation")
    public void testToString() {
        String str = guest.toString();
        assertNotNull(str);
        assertTrue(str.contains("Guest"));
        assertTrue(str.contains("GUEST1001"));
        assertTrue(str.contains("Tech Corporation"));
    }

    // ============ MULTIPLE GUESTS TESTS ============

    @Test
    @DisplayName("should create multiple guests with different IDs")
    public void testMultipleGuestsHaveUniqueIds() {
        Guest guest2 = new Guest("guest2@external.com", "Pass123!", "Physics",
                "GUEST2001", "Another Corp", "sponsor@anothercorp.com");
        assertNotEquals(guest.getUserId(), guest2.getUserId());
    }

    @Test
    @DisplayName("should maintain independent state between guests")
    public void testGuestIndependentState() {
        Guest guest2 = new Guest("guest2@external.com", "Pass123!", "Physics",
                "GUEST2001", "Another Corp", "sponsor@anothercorp.com");

        guest.setOrganization("NewOrg");
        guest.activate();

        assertNotEquals(guest.getOrganization(), guest2.getOrganization());
        assertNotEquals(guest.getAccountStatus(), guest2.getAccountStatus());
    }

    // ============ SPONSOR TRACKING TESTS ============

    @Test
    @DisplayName("should maintain sponsor email for tracking")
    public void testSponsorEmailTracking() {
        assertEquals("sponsor@techcorp.com", guest.getSponsorEmail());
        guest.setSponsorEmail("newsponsor@techcorp.com");
        assertEquals("newsponsor@techcorp.com", guest.getSponsorEmail());
    }

    @Test
    @DisplayName("should handle multiple guests from same organization")
    public void testMultipleGuestsSameOrganization() {
        Guest guest1 = new Guest("guest1@external.com", "Pass123!", "Eng",
                "G001", "Tech Corp", "s1@techcorp.com");
        Guest guest2 = new Guest("guest2@external.com", "Pass123!", "Eng",
                "G002", "Tech Corp", "s2@techcorp.com");

        assertEquals("Tech Corp", guest1.getOrganization());
        assertEquals("Tech Corp", guest2.getOrganization());
        assertNotEquals(guest1.getSponsorEmail(), guest2.getSponsorEmail());
    }

    // ============ EDGE CASE TESTS ============

    @Test
    @DisplayName("should handle empty organization")
    public void testEmptyOrganization() {
        guest.setOrganization("");
        assertEquals("", guest.getOrganization());
    }

    @Test
    @DisplayName("should handle empty guest ID")
    public void testEmptyGuestID() {
        guest.setGuestID("");
        assertEquals("", guest.getGuestID());
    }

    @Test
    @DisplayName("should handle empty sponsor email")
    public void testEmptySponsorEmail() {
        guest.setSponsorEmail("");
        assertEquals("", guest.getSponsorEmail());
    }

    @Test
    @DisplayName("should handle special characters in organization name")
    public void testSpecialCharactersInOrganization() {
        guest.setOrganization("Tech Corp & Co., Ltd.");
        assertEquals("Tech Corp & Co., Ltd.", guest.getOrganization());
    }
}
