package ca.yorku.eecs3311.model.user;

import ca.yorku.eecs3311.model.enums.AccountStatus;
import ca.yorku.eecs3311.model.enums.UserType;
import ca.yorku.eecs3311.model.equipment.Lab;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Test suite for Manager user type.
 */
public class ManagerManualTest {

    private Manager manager;

    @BeforeEach
    public void setUp() {
        manager = new Manager("manager@york.edu", "SecurePass123!", "EECS", "MGR1001");
    }

    // ============ CONSTRUCTOR TESTS ============

    @Test
    @DisplayName("should create Manager with correct properties")
    public void testManagerConstructor() {
        assertEquals("manager@york.edu", manager.getEmail());
        assertEquals("MGR1001", manager.getManagerID());
        assertEquals(UserType.MANAGER, manager.getUserType());
        assertEquals(AccountStatus.PENDING, manager.getAccountStatus());
    }

    @Test
    @DisplayName("should initialize empty labs and permissions lists")
    public void testInitializeEmptyCollections() {
        assertTrue(manager.getAssignedLabs().isEmpty());
        assertTrue(manager.getPermissions().isEmpty());
    }

    @Test
    @DisplayName("should auto-generate userId on construction")
    public void testAutoGeneratedUserId() {
        assertNotNull(manager.getUserId());
        assertFalse(manager.getUserId().isEmpty());
    }

    // ============ CREDENTIAL AND HOURLY RATE TESTS ============

    @Test
    @DisplayName("should return correct credential number (Manager ID)")
    public void testGetCredentialNumber() {
        assertEquals("MGR1001", manager.getCredentialNumber());
    }

    @Test
    @DisplayName("should return zero hourly rate for Manager")
    public void testGetHourlyRate() {
        assertEquals(0.00, manager.getHourlyRate());
    }

    // ============ GETTERS AND SETTERS TESTS ============

    @Test
    @DisplayName("should get and set Manager ID")
    public void testGetSetManagerID() {
        manager.setManagerID("MGR2001");
        assertEquals("MGR2001", manager.getManagerID());
        assertEquals("MGR2001", manager.getCredentialNumber());
    }

    @Test
    @DisplayName("should get and set Email")
    public void testGetSetEmail() {
        manager.setEmail("newmanager@york.edu");
        assertEquals("newmanager@york.edu", manager.getEmail());
    }

    @Test
    @DisplayName("should get and set Department")
    public void testGetSetDepartment() {
        manager.setDepartment("Electrical Engineering");
        assertEquals("Electrical Engineering", manager.getDepartment());
    }

    // ============ PERMISSION MANAGEMENT TESTS ============

    @Test
    @DisplayName("should add single permission")
    public void testAddPermission() {
        manager.addPermission("MANAGE_BOOKINGS");
        assertTrue(manager.hasPermission("MANAGE_BOOKINGS"));
        assertEquals(1, manager.getPermissions().size());
    }

    @Test
    @DisplayName("should add multiple permissions")
    public void testAddMultiplePermissions() {
        manager.addPermission("MANAGE_BOOKINGS");
        manager.addPermission("MANAGE_EQUIPMENT");
        manager.addPermission("APPROVE_USERS");

        assertEquals(3, manager.getPermissions().size());
        assertTrue(manager.hasPermission("MANAGE_BOOKINGS"));
        assertTrue(manager.hasPermission("MANAGE_EQUIPMENT"));
        assertTrue(manager.hasPermission("APPROVE_USERS"));
    }

    @Test
    @DisplayName("should not add duplicate permissions")
    public void testNoDuplicatePermissions() {
        manager.addPermission("MANAGE_BOOKINGS");
        manager.addPermission("MANAGE_BOOKINGS");
        manager.addPermission("MANAGE_BOOKINGS");

        assertEquals(1, manager.getPermissions().size());
    }

    @Test
    @DisplayName("should remove permission")
    public void testRemovePermission() {
        manager.addPermission("MANAGE_BOOKINGS");
        manager.addPermission("MANAGE_EQUIPMENT");
        manager.removePermission("MANAGE_BOOKINGS");

        assertFalse(manager.hasPermission("MANAGE_BOOKINGS"));
        assertTrue(manager.hasPermission("MANAGE_EQUIPMENT"));
        assertEquals(1, manager.getPermissions().size());
    }

    @Test
    @DisplayName("should return false for non-existent permission")
    public void testHasPermissionNonExistent() {
        manager.addPermission("MANAGE_BOOKINGS");
        assertFalse(manager.hasPermission("MANAGE_EQUIPMENT"));
    }

    @Test
    @DisplayName("should handle removing non-existent permission")
    public void testRemoveNonExistentPermission() {
        manager.addPermission("MANAGE_BOOKINGS");
        manager.removePermission("NON_EXISTENT");

        assertEquals(1, manager.getPermissions().size());
        assertTrue(manager.hasPermission("MANAGE_BOOKINGS"));
    }

    // ============ LAB ASSIGNMENT TESTS ============

    @Test
    @DisplayName("should assign lab to manager")
    public void testAssignLab() {
        Lab lab = new Lab("Lab001", "Physics Lab", "Building A", 10);
        manager.assignLab(lab);

        assertEquals(1, manager.getAssignedLabs().size());
        assertTrue(manager.getAssignedLabs().contains(lab));
    }

    @Test
    @DisplayName("should assign multiple labs")
    public void testAssignMultipleLabs() {
        Lab lab1 = new Lab("Lab001", "Physics Lab", "Building A", 10);
        Lab lab2 = new Lab("Lab002", "Chemistry Lab", "Building B", 15);
        Lab lab3 = new Lab("Lab003", "Biology Lab", "Building C", 20);

        manager.assignLab(lab1);
        manager.assignLab(lab2);
        manager.assignLab(lab3);

        assertEquals(3, manager.getAssignedLabs().size());
    }

    @Test
    @DisplayName("should not add duplicate lab assignments")
    public void testNoDuplicateLabAssignments() {
        Lab lab = new Lab("Lab001", "Physics Lab", "Building A", 10);
        manager.assignLab(lab);
        manager.assignLab(lab);
        manager.assignLab(lab);

        assertEquals(1, manager.getAssignedLabs().size());
    }

    @Test
    @DisplayName("should remove lab assignment")
    public void testRemoveLab() {
        Lab lab1 = new Lab("Lab001", "Physics Lab", "Building A", 10);
        Lab lab2 = new Lab("Lab002", "Chemistry Lab", "Building B", 15);

        manager.assignLab(lab1);
        manager.assignLab(lab2);
        manager.removeLab(lab1);

        assertEquals(1, manager.getAssignedLabs().size());
        assertTrue(manager.getAssignedLabs().contains(lab2));
        assertFalse(manager.getAssignedLabs().contains(lab1));
    }

    // ============ ACCOUNT STATUS TESTS ============

    @Test
    @DisplayName("should activate Manager account")
    public void testActivateAccount() {
        manager.activate();
        assertEquals(AccountStatus.ACTIVE, manager.getAccountStatus());
        assertTrue(manager.isActive());
    }

    @Test
    @DisplayName("should suspend Manager account")
    public void testSuspendAccount() {
        manager.suspend();
        assertEquals(AccountStatus.SUSPENDED, manager.getAccountStatus());
        assertFalse(manager.isActive());
    }

    // ============ CREDENTIAL VALIDATION TESTS ============

    @Test
    @DisplayName("should validate correct credentials")
    public void testValidateCredentialsCorrect() {
        assertTrue(manager.validateCredentials("manager@york.edu", "SecurePass123!"));
    }

    @Test
    @DisplayName("should reject incorrect password")
    public void testValidateCredentialsIncorrectPassword() {
        assertFalse(manager.validateCredentials("manager@york.edu", "WrongPass123!"));
    }

    // ============ PROFILE UPDATE TESTS ============

    @Test
    @DisplayName("should update profile email and department")
    public void testUpdateProfile() {
        manager.updateProfile("newmanager@york.edu", "Computer Science");
        assertEquals("newmanager@york.edu", manager.getEmail());
        assertEquals("Computer Science", manager.getDepartment());
    }

    // ============ CSV CONSTRUCTOR TESTS ============

    @Test
    @DisplayName("should construct Manager from CSV")
    public void testCSVConstructor() {
        LocalDateTime regDate = LocalDateTime.now().minusDays(30);
        Manager csvManager = new Manager("mgr-uuid-123", "manager@york.edu", "Pass123!",
                AccountStatus.ACTIVE, regDate, "EECS", "MGR1001");

        assertEquals("mgr-uuid-123", csvManager.getUserId());
        assertEquals("MGR1001", csvManager.getManagerID());
        assertEquals(AccountStatus.ACTIVE, csvManager.getAccountStatus());
        assertTrue(csvManager.getAssignedLabs().isEmpty());
        assertTrue(csvManager.getPermissions().isEmpty());
    }

    // ============ STRING REPRESENTATION TESTS ============

    @Test
    @DisplayName("should generate meaningful toString representation")
    public void testToString() {
        String str = manager.toString();
        assertNotNull(str);
        assertTrue(str.contains("Manager"));
        assertTrue(str.contains("MGR1001"));
    }

    // ============ MULTIPLE MANAGERS TESTS ============

    @Test
    @DisplayName("should create multiple managers with different IDs")
    public void testMultipleManagersHaveUniqueIds() {
        Manager manager2 = new Manager("manager2@york.edu", "Pass123!", "Physics", "MGR2001");
        assertNotEquals(manager.getUserId(), manager2.getUserId());
    }

    @Test
    @DisplayName("should maintain independent state between managers")
    public void testManagerIndependentState() {
        Manager manager2 = new Manager("manager2@york.edu", "Pass123!", "Physics", "MGR2001");

        manager.addPermission("MANAGE_BOOKINGS");
        Lab lab1 = new Lab("Lab001", "Physics Lab", "Building A", 10);
        manager.assignLab(lab1);

        assertTrue(manager.getPermissions().isEmpty() || manager.getPermissions().size() > manager2.getPermissions().size());
        assertTrue(manager.getAssignedLabs().isEmpty() || manager.getAssignedLabs().size() > manager2.getAssignedLabs().size());
    }

    // ============ STATE MANAGEMENT TESTS ============

    @Test
    @DisplayName("should set entire assignment list")
    public void testSetAssignedLabs() {
        Lab lab1 = new Lab("Lab001", "Physics Lab", "Building A", 10);
        Lab lab2 = new Lab("Lab002", "Chemistry Lab", "Building B", 15);
        
        java.util.List<Lab> labs = new java.util.ArrayList<>();
        labs.add(lab1);
        labs.add(lab2);
        
        manager.setAssignedLabs(labs);
        assertEquals(2, manager.getAssignedLabs().size());
    }

    @Test
    @DisplayName("should set entire permissions list")
    public void testSetPermissions() {
        java.util.List<String> perms = new java.util.ArrayList<>();
        perms.add("MANAGE_BOOKINGS");
        perms.add("MANAGE_EQUIPMENT");
        perms.add("VIEW_REPORTS");
        
        manager.setPermissions(perms);
        assertEquals(3, manager.getPermissions().size());
        assertTrue(manager.hasPermission("VIEW_REPORTS"));
    }

    // ============ EDGE CASE TESTS ============

    @Test
    @DisplayName("should handle empty manager ID")
    public void testEmptyManagerID() {
        manager.setManagerID("");
        assertEquals("", manager.getManagerID());
    }

    @Test
    @DisplayName("should handle empty permission string")
    public void testEmptyPermissionString() {
        manager.addPermission("");
        assertTrue(manager.hasPermission(""));
    }
}
