package ca.yorku.eecs3311.model.user;

import ca.yorku.eecs3311.model.enums.AccountStatus;
import ca.yorku.eecs3311.model.enums.UserType;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Test suite for Researcher user type.
 */
public class ResearcherManualTest {

    private Researcher researcher;

    @BeforeEach
    public void setUp() {
        researcher = new Researcher("researcher@york.edu", "SecurePass123!", "Computer Science",
                "RES1001", "Machine Learning", "GRANT-2024-001");
    }

    // ============ CONSTRUCTOR TESTS ============

    @Test
    @DisplayName("should create Researcher with correct properties")
    public void testResearcherConstructor() {
        assertEquals("researcher@york.edu", researcher.getEmail());
        assertEquals("RES1001", researcher.getResearcherID());
        assertEquals("Machine Learning", researcher.getResearchArea());
        assertEquals("GRANT-2024-001", researcher.getGrantNumber());
        assertEquals(UserType.RESEARCHER, researcher.getUserType());
        assertEquals(AccountStatus.PENDING, researcher.getAccountStatus());
    }

    @Test
    @DisplayName("should auto-generate userId on construction")
    public void testAutoGeneratedUserId() {
        assertNotNull(researcher.getUserId());
        assertFalse(researcher.getUserId().isEmpty());
    }

    // ============ CREDENTIAL AND HOURLY RATE TESTS ============

    @Test
    @DisplayName("should return correct credential number (Researcher ID)")
    public void testGetCredentialNumber() {
        assertEquals("RES1001", researcher.getCredentialNumber());
    }

    @Test
    @DisplayName("should return correct hourly rate for Researcher (8.00)")
    public void testGetHourlyRate() {
        assertEquals(8.00, researcher.getHourlyRate());
    }

    @Test
    @DisplayName("should have hourly rate between Student and Faculty")
    public void testResearcherHourlyRateBetweenOthers() {
        Student student = new Student("s@york.edu", "Pass123!", "CS", "S001", "EECS", 1);
        Faculty faculty = new Faculty("f@york.edu", "Pass123!", "CS", "F001", "Prof");
        assertTrue(researcher.getHourlyRate() > student.getHourlyRate());
        assertTrue(researcher.getHourlyRate() < faculty.getHourlyRate());
    }

    // ============ GETTERS AND SETTERS TESTS ============

    @Test
    @DisplayName("should get and set Researcher ID")
    public void testGetSetResearcherID() {
        researcher.setResearcherID("RES2001");
        assertEquals("RES2001", researcher.getResearcherID());
        assertEquals("RES2001", researcher.getCredentialNumber());
    }

    @Test
    @DisplayName("should get and set Research Area")
    public void testGetSetResearchArea() {
        researcher.setResearchArea("Natural Language Processing");
        assertEquals("Natural Language Processing", researcher.getResearchArea());
    }

    @Test
    @DisplayName("should get and set Grant Number")
    public void testGetSetGrantNumber() {
        researcher.setGrantNumber("GRANT-2025-002");
        assertEquals("GRANT-2025-002", researcher.getGrantNumber());
    }

    @Test
    @DisplayName("should get and set Email")
    public void testGetSetEmail() {
        researcher.setEmail("newresearcher@york.edu");
        assertEquals("newresearcher@york.edu", researcher.getEmail());
    }

    @Test
    @DisplayName("should get and set Department")
    public void testGetSetDepartment() {
        researcher.setDepartment("Electrical Engineering");
        assertEquals("Electrical Engineering", researcher.getDepartment());
    }

    // ============ ACCOUNT STATUS TESTS ============

    @Test
    @DisplayName("should activate Researcher account")
    public void testActivateAccount() {
        researcher.activate();
        assertEquals(AccountStatus.ACTIVE, researcher.getAccountStatus());
        assertTrue(researcher.isActive());
    }

    @Test
    @DisplayName("should suspend Researcher account")
    public void testSuspendAccount() {
        researcher.suspend();
        assertEquals(AccountStatus.SUSPENDED, researcher.getAccountStatus());
        assertFalse(researcher.isActive());
    }

    @Test
    @DisplayName("should deactivate Researcher account")
    public void testDeactivateAccount() {
        researcher.deactivate();
        assertEquals(AccountStatus.DEACTIVATED, researcher.getAccountStatus());
    }

    // ============ CREDENTIAL VALIDATION TESTS ============

    @Test
    @DisplayName("should validate correct credentials")
    public void testValidateCredentialsCorrect() {
        assertTrue(researcher.validateCredentials("researcher@york.edu", "SecurePass123!"));
    }

    @Test
    @DisplayName("should reject incorrect password")
    public void testValidateCredentialsIncorrectPassword() {
        assertFalse(researcher.validateCredentials("researcher@york.edu", "WrongPass123!"));
    }

    @Test
    @DisplayName("should reject incorrect email")
    public void testValidateCredentialsIncorrectEmail() {
        assertFalse(researcher.validateCredentials("wrong@york.edu", "SecurePass123!"));
    }

    // ============ PROFILE UPDATE TESTS ============

    @Test
    @DisplayName("should update profile email and department")
    public void testUpdateProfile() {
        researcher.updateProfile("newres@york.edu", "Electrical Engineering");
        assertEquals("newres@york.edu", researcher.getEmail());
        assertEquals("Electrical Engineering", researcher.getDepartment());
    }

    @Test
    @DisplayName("should not update grant info via updateProfile")
    public void testUpdateProfileDoesNotAffectGrant() {
        String originalGrant = researcher.getGrantNumber();
        researcher.updateProfile("newres@york.edu", "New Dept");
        assertEquals(originalGrant, researcher.getGrantNumber());
    }

    // ============ CSV CONSTRUCTOR TESTS ============

    @Test
    @DisplayName("should construct Researcher from CSV")
    public void testCSVConstructor() {
        LocalDateTime regDate = LocalDateTime.now().minusDays(15);
        Researcher csvResearcher = new Researcher("res-uuid-123", "researcher@york.edu", "Pass123!",
                AccountStatus.ACTIVE, regDate, "Computer Science",
                "RES1001", "AI", "GRANT-2024-001");

        assertEquals("res-uuid-123", csvResearcher.getUserId());
        assertEquals("RES1001", csvResearcher.getResearcherID());
        assertEquals("AI", csvResearcher.getResearchArea());
        assertEquals("GRANT-2024-001", csvResearcher.getGrantNumber());
        assertEquals(AccountStatus.ACTIVE, csvResearcher.getAccountStatus());
    }

    // ============ STRING REPRESENTATION TESTS ============

    @Test
    @DisplayName("should generate meaningful toString representation")
    public void testToString() {
        String str = researcher.toString();
        assertNotNull(str);
        assertTrue(str.contains("Researcher"));
        assertTrue(str.contains("RES1001"));
        assertTrue(str.contains("Machine Learning"));
    }

    // ============ MULTIPLE RESEARCHERS TESTS ============

    @Test
    @DisplayName("should create multiple researchers with different IDs")
    public void testMultipleResearchersHaveUniqueIds() {
        Researcher researcher2 = new Researcher("res2@york.edu", "Pass123!", "Physics",
                "RES2001", "Quantum Physics", "GRANT-2024-002");
        assertNotEquals(researcher.getUserId(), researcher2.getUserId());
    }

    @Test
    @DisplayName("should maintain independent state between researchers")
    public void testResearcherIndependentState() {
        Researcher researcher2 = new Researcher("res2@york.edu", "Pass123!", "Physics",
                "RES2001", "Quantum Physics", "GRANT-2024-002");

        researcher.setResearchArea("NLP");
        researcher.activate();

        assertNotEquals(researcher.getResearchArea(), researcher2.getResearchArea());
        assertNotEquals(researcher.getAccountStatus(), researcher2.getAccountStatus());
    }

    // ============ EDGE CASE TESTS ============

    @Test
    @DisplayName("should handle empty research area")
    public void testEmptyResearchArea() {
        researcher.setResearchArea("");
        assertEquals("", researcher.getResearchArea());
    }

    @Test
    @DisplayName("should handle empty grant number")
    public void testEmptyGrantNumber() {
        researcher.setGrantNumber("");
        assertEquals("", researcher.getGrantNumber());
    }

    @Test
    @DisplayName("should handle empty researcher ID")
    public void testEmptyResearcherID() {
        researcher.setResearcherID("");
        assertEquals("", researcher.getResearcherID());
    }

    @Test
    @DisplayName("should handle special characters in research area")
    public void testSpecialCharactersInResearchArea() {
        researcher.setResearchArea("AI/ML & Deep Learning (NLP)");
        assertEquals("AI/ML & Deep Learning (NLP)", researcher.getResearchArea());
    }
}
