package ca.yorku.eecs3311.model.user;

import ca.yorku.eecs3311.model.enums.AccountStatus;
import ca.yorku.eecs3311.model.enums.UserType;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Test suite for Student user type, covering all properties and methods.
 */
public class StudentManualTest {

    private Student student;

    @BeforeEach
    public void setUp() {
        student = new Student("student@york.edu", "SecurePass123!", "Computer Science",
                "STUD1001", "EECS", 2);
    }

    // ============ CONSTRUCTOR TESTS ============

    @Test
    @DisplayName("should create Student with correct basic properties")
    public void testStudentConstructor() {
        assertEquals("student@york.edu", student.getEmail());
        assertEquals("STUD1001", student.getStudentID());
        assertEquals("EECS", student.getProgram());
        assertEquals(2, student.getYearOfStudy());
        assertEquals(UserType.STUDENT, student.getUserType());
        assertEquals(AccountStatus.PENDING, student.getAccountStatus());
    }

    @Test
    @DisplayName("should set PENDING status by default on construction")
    public void testDefaultPendingStatus() {
        assertEquals(AccountStatus.PENDING, student.getAccountStatus());
    }

    @Test
    @DisplayName("should auto-generate userId on construction")
    public void testAutoGeneratedUserId() {
        assertNotNull(student.getUserId());
        assertFalse(student.getUserId().isEmpty());
        assertTrue(student.getUserId().length() > 0);
    }

    @Test
    @DisplayName("should set registration date on construction")
    public void testRegistrationDateSet() {
        LocalDateTime regDate = student.getRegistrationDate();
        assertNotNull(regDate);
        LocalDateTime now = LocalDateTime.now();
        assertTrue(regDate.isBefore(now) || regDate.equals(now));
    }

    // ============ CREDENTIAL AND HOURLY RATE TESTS ============

    @Test
    @DisplayName("should return correct credential number (Student ID)")
    public void testGetCredentialNumber() {
        assertEquals("STUD1001", student.getCredentialNumber());
    }

    @Test
    @DisplayName("should return correct hourly rate for Student (5.00)")
    public void testGetHourlyRate() {
        assertEquals(5.00, student.getHourlyRate());
    }

    @Test
    @DisplayName("should maintain hourly rate consistency")
    public void testHourlyRateConsistency() {
        Student student1 = new Student("s1@york.edu", "Pass123!", "CS", "S001", "EECS", 1);
        Student student2 = new Student("s2@york.edu", "Pass123!", "CS", "S002", "MATH", 4);
        assertEquals(student1.getHourlyRate(), student2.getHourlyRate());
    }

    // ============ GETTERS AND SETTERS TESTS ============

    @Test
    @DisplayName("should get and set Student ID")
    public void testGetSetStudentID() {
        student.setStudentID("STUD2001");
        assertEquals("STUD2001", student.getStudentID());
        assertEquals("STUD2001", student.getCredentialNumber());
    }

    @Test
    @DisplayName("should get and set Program")
    public void testGetSetProgram() {
        student.setProgram("Software Engineering");
        assertEquals("Software Engineering", student.getProgram());
    }

    @Test
    @DisplayName("should get and set Year of Study")
    public void testGetSetYearOfStudy() {
        student.setYearOfStudy(4);
        assertEquals(4, student.getYearOfStudy());
    }

    @Test
    @DisplayName("should handle year of study 1-4")
    public void testYearOfStudyRange() {
        for (int year = 1; year <= 4; year++) {
            student.setYearOfStudy(year);
            assertEquals(year, student.getYearOfStudy());
        }
    }

    @Test
    @DisplayName("should get and set Email via inherited method")
    public void testGetSetEmail() {
        student.setEmail("newemail@york.edu");
        assertEquals("newemail@york.edu", student.getEmail());
    }

    @Test
    @DisplayName("should get and set Password via inherited method")
    public void testGetSetPassword() {
        student.setPassword("NewPass456!");
        assertEquals("NewPass456!", student.getPassword());
    }

    @Test
    @DisplayName("should get and set Department via inherited method")
    public void testGetSetDepartment() {
        student.setDepartment("Electrical Engineering");
        assertEquals("Electrical Engineering", student.getDepartment());
    }

    // ============ ACCOUNT STATUS TESTS ============

    @Test
    @DisplayName("should activate Student account")
    public void testActivateAccount() {
        student.activate();
        assertEquals(AccountStatus.ACTIVE, student.getAccountStatus());
        assertTrue(student.isActive());
    }

    @Test
    @DisplayName("should suspend Student account")
    public void testSuspendAccount() {
        student.suspend();
        assertEquals(AccountStatus.SUSPENDED, student.getAccountStatus());
        assertFalse(student.isActive());
    }

    @Test
    @DisplayName("should deactivate Student account")
    public void testDeactivateAccount() {
        student.deactivate();
        assertEquals(AccountStatus.DEACTIVATED, student.getAccountStatus());
        assertFalse(student.isActive());
    }

    @Test
    @DisplayName("should transition between account statuses")
    public void testAccountStatusTransitions() {
        assertEquals(AccountStatus.PENDING, student.getAccountStatus());
        student.activate();
        assertEquals(AccountStatus.ACTIVE, student.getAccountStatus());
        student.suspend();
        assertEquals(AccountStatus.SUSPENDED, student.getAccountStatus());
        student.activate();
        assertEquals(AccountStatus.ACTIVE, student.getAccountStatus());
    }

    // ============ CREDENTIAL VALIDATION TESTS ============

    @Test
    @DisplayName("should validate correct credentials")
    public void testValidateCredentialsCorrect() {
        assertTrue(student.validateCredentials("student@york.edu", "SecurePass123!"));
    }

    @Test
    @DisplayName("should reject incorrect password")
    public void testValidateCredentialsIncorrectPassword() {
        assertFalse(student.validateCredentials("student@york.edu", "WrongPass123!"));
    }

    @Test
    @DisplayName("should reject incorrect email")
    public void testValidateCredentialsIncorrectEmail() {
        assertFalse(student.validateCredentials("wrong@york.edu", "SecurePass123!"));
    }

    @Test
    @DisplayName("should perform case-sensitive email validation")
    public void testValidateCredentialsCaseSensitiveEmail() {
        assertFalse(student.validateCredentials("STUDENT@YORK.EDU", "SecurePass123!"));
    }

    // ============ PROFILE UPDATE TESTS ============

    @Test
    @DisplayName("should update profile email and department")
    public void testUpdateProfile() {
        student.updateProfile("newemail@york.edu", "Electrical Engineering");
        assertEquals("newemail@york.edu", student.getEmail());
        assertEquals("Electrical Engineering", student.getDepartment());
    }

    @Test
    @DisplayName("should not update other fields via updateProfile")
    public void testUpdateProfileDoesNotAffectOtherFields() {
        String originalStudentId = student.getStudentID();
        String originalProgram = student.getProgram();
        student.updateProfile("newemail@york.edu", "New Dept");
        assertEquals(originalStudentId, student.getStudentID());
        assertEquals(originalProgram, student.getProgram());
    }

    // ============ CSV CONSTRUCTOR TESTS ============

    @Test
    @DisplayName("should construct Student from CSV with provided userId")
    public void testCSVConstructor() {
        LocalDateTime regDate = LocalDateTime.now().minusDays(5);
        Student csvStudent = new Student("user-uuid-123", "student@york.edu", "Pass123!",
                AccountStatus.ACTIVE, regDate, "Computer Science",
                "STUD1001", "EECS", 3);

        assertEquals("user-uuid-123", csvStudent.getUserId());
        assertEquals("student@york.edu", csvStudent.getEmail());
        assertEquals("Pass123!", csvStudent.getPassword());
        assertEquals(AccountStatus.ACTIVE, csvStudent.getAccountStatus());
        assertEquals("EECS", csvStudent.getProgram());
        assertEquals(3, csvStudent.getYearOfStudy());
    }

    @Test
    @DisplayName("should preserve registration date from CSV")
    public void testCSVConstructorPreservesRegistrationDate() {
        LocalDateTime regDate = LocalDateTime.of(2024, 1, 15, 10, 30);
        Student csvStudent = new Student("user-uuid-123", "student@york.edu", "Pass123!",
                AccountStatus.PENDING, regDate, "CS", "STUD1001", "EECS", 1);

        assertEquals(regDate, csvStudent.getRegistrationDate());
    }

    // ============ STRING REPRESENTATION TESTS ============

    @Test
    @DisplayName("should generate meaningful toString representation")
    public void testToString() {
        String str = student.toString();
        assertNotNull(str);
        assertTrue(str.contains("Student"));
        assertTrue(str.contains("STUD1001"));
        assertTrue(str.contains("EECS"));
    }

    // ============ MULTIPLE STUDENTS TESTS ============

    @Test
    @DisplayName("should create multiple students with different IDs")
    public void testMultipleStudentsHaveUniqueIds() {
        Student student2 = new Student("student2@york.edu", "Pass123!", "Physics",
                "STUD2001", "Physics", 1);
        assertNotEquals(student.getUserId(), student2.getUserId());
    }

    @Test
    @DisplayName("should maintain independent state between students")
    public void testStudentIndependentState() {
        Student student2 = new Student("student2@york.edu", "Pass123!", "Physics",
                "STUD2001", "Physics", 1);

        student.activate();
        student.setProgram("Software Engineering");

        assertNotEquals(student.getAccountStatus(), student2.getAccountStatus());
        assertNotEquals(student.getProgram(), student2.getProgram());
    }

    // ============ EDGE CASE TESTS ============

    @Test
    @DisplayName("should handle empty string program")
    public void testEmptyProgram() {
        student.setProgram("");
        assertEquals("", student.getProgram());
    }

    @Test
    @DisplayName("should handle empty string student ID")
    public void testEmptyStudentID() {
        student.setStudentID("");
        assertEquals("", student.getStudentID());
    }

    @Test
    @DisplayName("should handle zero year of study")
    public void testZeroYearOfStudy() {
        student.setYearOfStudy(0);
        assertEquals(0, student.getYearOfStudy());
    }

    @Test
    @DisplayName("should handle large year of study values")
    public void testLargeYearOfStudy() {
        student.setYearOfStudy(99);
        assertEquals(99, student.getYearOfStudy());
    }
}
