package ca.yorku.eecs3311.model.user;

import ca.yorku.eecs3311.model.enums.AccountStatus;
import ca.yorku.eecs3311.model.enums.UserType;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Test suite for SystemAdministrator user type.
 */
public class SystemAdministratorManualTest {

    private SystemAdministrator admin;

    @BeforeEach
    public void setUp() {
        admin = new SystemAdministrator("admin@york.edu", "SecurePass123!", "IT",
                "MGR-ADMIN-001", "ADMIN001", true);
    }

    // ============ CONSTRUCTOR TESTS ============

    @Test
    @DisplayName("should create SystemAdministrator with correct properties")
    public void testAdminConstructor() {
        assertEquals("admin@york.edu", admin.getEmail());
        assertEquals("ADMIN001", admin.getAdminID());
        assertTrue(admin.isHeadCoordinator());
        assertEquals(UserType.ADMIN, admin.getUserType());
        assertEquals(AccountStatus.ACTIVE, admin.getAccountStatus());
    }

    @Test
    @DisplayName("should auto-generate userId on construction")
    public void testAutoGeneratedUserId() {
        assertNotNull(admin.getUserId());
        assertFalse(admin.getUserId().isEmpty());
    }

    @Test
    @DisplayName("should have Manager ID (inherited)")
    public void testHasManagerID() {
        assertEquals("MGR-ADMIN-001", admin.getCredentialNumber());
    }

    // ============ USER TYPE TESTS ============

    @Test
    @DisplayName("should report user type as ADMIN")
    public void testUserTypeIsAdmin() {
        assertEquals(UserType.ADMIN, admin.getUserType());
    }

    @Test
    @DisplayName("should be instance of both Manager and SystemAdministrator")
    public void testInheritanceHierarchy() {
        assertInstanceOf(Manager.class, admin);
        assertInstanceOf(SystemAdministrator.class, admin);
        assertInstanceOf(User.class, admin);
    }

    // ============ CREDENTIAL AND HOURLY RATE TESTS ============

    @Test
    @DisplayName("should return admin ID as credential number")
    public void testGetCredentialNumberReturnsAdminID() {
        assertEquals("ADMIN001", admin.getAdminID());
    }

    @Test
    @DisplayName("should return zero hourly rate (inherited from Manager)")
    public void testGetHourlyRate() {
        assertEquals(0.00, admin.getHourlyRate());
    }

    // ============ ADMIN SPECIFIC TESTS ============

    @Test
    @DisplayName("should get admin ID")
    public void testGetAdminID() {
        assertEquals("ADMIN001", admin.getAdminID());
    }

    @Test
    @DisplayName("should set admin ID")
    public void testSetAdminID() {
        admin.setAdminID("ADMIN002");
        assertEquals("ADMIN002", admin.getAdminID());
    }

    @Test
    @DisplayName("should check if head coordinator")
    public void testIsHeadCoordinator() {
        assertTrue(admin.isHeadCoordinator());
    }

    @Test
    @DisplayName("should set head coordinator status to false")
    public void testSetHeadCoordinatorFalse() {
        admin.setHeadCoordinator(false);
        assertFalse(admin.isHeadCoordinator());
    }

    @Test
    @DisplayName("should set head coordinator status to true")
    public void testSetHeadCoordinatorTrue() {
        SystemAdministrator nonHeadAdmin = new SystemAdministrator("admin2@york.edu", "Pass123!", "IT",
                "MGR-ADMIN-002", "ADMIN002", false);
        assertFalse(nonHeadAdmin.isHeadCoordinator());
        
        nonHeadAdmin.setHeadCoordinator(true);
        assertTrue(nonHeadAdmin.isHeadCoordinator());
    }

    // ============ INHERITED MANAGER FUNCTIONALITY TESTS ============

    @Test
    @DisplayName("should inherit permission management from Manager")
    public void testInheritedPermissionManagement() {
        admin.addPermission("MANAGE_USERS");
        admin.addPermission("MANAGE_SYSTEM");

        assertTrue(admin.hasPermission("MANAGE_USERS"));
        assertTrue(admin.hasPermission("MANAGE_SYSTEM"));
        assertEquals(2, admin.getPermissions().size());
    }

    @Test
    @DisplayName("should inherit lab assignment from Manager")
    public void testInheritedLabAssignment() {
        ca.yorku.eecs3311.model.equipment.Lab lab = 
            new ca.yorku.eecs3311.model.equipment.Lab("Lab001", "Physics Lab", "Building A", 10);
        
        admin.assignLab(lab);
        assertEquals(1, admin.getAssignedLabs().size());
        assertTrue(admin.getAssignedLabs().contains(lab));
    }

    // ============ ACCOUNT STATUS TESTS ============

    @Test
    @DisplayName("should have ACTIVE status by default")
    public void testDefaultActiveStatus() {
        assertEquals(AccountStatus.ACTIVE, admin.getAccountStatus());
        assertTrue(admin.isActive());
    }

    @Test
    @DisplayName("should be able to suspend admin account")
    public void testSuspendAdminAccount() {
        admin.suspend();
        assertEquals(AccountStatus.SUSPENDED, admin.getAccountStatus());
        assertFalse(admin.isActive());
    }

    @Test
    @DisplayName("should be able to deactivate admin account")
    public void testDeactivateAdminAccount() {
        admin.deactivate();
        assertEquals(AccountStatus.DEACTIVATED, admin.getAccountStatus());
        assertFalse(admin.isActive());
    }

    // ============ CREDENTIAL VALIDATION TESTS ============

    @Test
    @DisplayName("should validate correct credentials")
    public void testValidateCredentialsCorrect() {
        assertTrue(admin.validateCredentials("admin@york.edu", "SecurePass123!"));
    }

    @Test
    @DisplayName("should reject incorrect password")
    public void testValidateCredentialsIncorrectPassword() {
        assertFalse(admin.validateCredentials("admin@york.edu", "WrongPass123!"));
    }

    @Test
    @DisplayName("should reject incorrect email")
    public void testValidateCredentialsIncorrectEmail() {
        assertFalse(admin.validateCredentials("wrong@york.edu", "SecurePass123!"));
    }

    // ============ PROFILE UPDATE TESTS ============

    @Test
    @DisplayName("should update profile email and department")
    public void testUpdateProfile() {
        admin.updateProfile("newadmin@york.edu", "Computer Science");
        assertEquals("newadmin@york.edu", admin.getEmail());
        assertEquals("Computer Science", admin.getDepartment());
    }

    // ============ CSV CONSTRUCTOR TESTS ============

    @Test
    @DisplayName("should construct SystemAdministrator from CSV")
    public void testCSVConstructor() {
        LocalDateTime regDate = LocalDateTime.now().minusDays(60);
        SystemAdministrator csvAdmin = new SystemAdministrator("admin-uuid-123", "admin@york.edu", "Pass123!",
                AccountStatus.ACTIVE, regDate, "IT",
                "MGR-ADMIN-001", "ADMIN001", true);

        assertEquals("admin-uuid-123", csvAdmin.getUserId());
        assertEquals("ADMIN001", csvAdmin.getAdminID());
        assertTrue(csvAdmin.isHeadCoordinator());
        assertEquals(AccountStatus.ACTIVE, csvAdmin.getAccountStatus());
        assertEquals(UserType.ADMIN, csvAdmin.getUserType());
    }

    @Test
    @DisplayName("should construct non-head-coordinator from CSV")
    public void testCSVConstructorNonHeadCoordinator() {
        LocalDateTime regDate = LocalDateTime.now().minusDays(60);
        SystemAdministrator csvAdmin = new SystemAdministrator("admin-uuid-124", "admin2@york.edu", "Pass123!",
                AccountStatus.ACTIVE, regDate, "IT",
                "MGR-ADMIN-002", "ADMIN002", false);

        assertFalse(csvAdmin.isHeadCoordinator());
    }

    // ============ INHERITANCE TESTS ============

    @Test
    @DisplayName("should call setAccountStatus on Manager superclass")
    public void testSetAccountStatus() {
        admin.setAccountStatus(AccountStatus.SUSPENDED);
        assertEquals(AccountStatus.SUSPENDED, admin.getAccountStatus());
    }

    @Test
    @DisplayName("should get and set email via inherited method")
    public void testGetSetEmail() {
        admin.setEmail("newemail@york.edu");
        assertEquals("newemail@york.edu", admin.getEmail());
    }

    @Test
    @DisplayName("should get and set department via inherited method")
    public void testGetSetDepartment() {
        admin.setDepartment("Information Technology");
        assertEquals("Information Technology", admin.getDepartment());
    }

    // ============ STRING REPRESENTATION TESTS ============

    @Test
    @DisplayName("should generate meaningful toString representation")
    public void testToString() {
        String str = admin.toString();
        assertNotNull(str);
        assertTrue(str.contains("SystemAdministrator"));
        assertTrue(str.contains("ADMIN001"));
        assertTrue(str.contains("true"));
    }

    // ============ MULTIPLE ADMINS TESTS ============

    @Test
    @DisplayName("should create multiple admins with different IDs")
    public void testMultipleAdminsHaveUniqueIds() {
        SystemAdministrator admin2 = new SystemAdministrator("admin2@york.edu", "Pass123!", "IT",
                "MGR-ADMIN-002", "ADMIN002", false);
        assertNotEquals(admin.getUserId(), admin2.getUserId());
    }

    @Test
    @DisplayName("should support head and non-head coordinators")
    public void testHeadAndNonHeadCoordinators() {
        SystemAdministrator headAdmin = new SystemAdministrator("head@york.edu", "Pass123!", "IT",
                "MGR-HEAD", "ADMIN-HEAD", true);
        SystemAdministrator regularAdmin = new SystemAdministrator("regular@york.edu", "Pass123!", "IT",
                "MGR-REGULAR", "ADMIN-REGULAR", false);

        assertTrue(headAdmin.isHeadCoordinator());
        assertFalse(regularAdmin.isHeadCoordinator());
        assertEquals(headAdmin.getUserType(), regularAdmin.getUserType());
    }

    // ============ SPECIAL ADMIN FUNCTIONALITY TESTS ============

    @Test
    @DisplayName("should maintain admin privileges independent of head coordinator status")
    public void testAdminPrivilegesIndependent() {
        SystemAdministrator admin1 = new SystemAdministrator("a1@york.edu", "Pass123!", "IT",
                "M1", "A1", true);
        SystemAdministrator admin2 = new SystemAdministrator("a2@york.edu", "Pass123!", "IT",
                "M2", "A2", false);

        admin1.addPermission("DELETE_USERS");
        admin2.addPermission("DELETE_USERS");

        assertEquals(1, admin1.getPermissions().size());
        assertEquals(1, admin2.getPermissions().size());
    }

    // ============ EDGE CASE TESTS ============

    @Test
    @DisplayName("should handle empty admin ID")
    public void testEmptyAdminID() {
        admin.setAdminID("");
        assertEquals("", admin.getAdminID());
    }

    @Test
    @DisplayName("should toggle head coordinator status multiple times")
    public void testToggleHeadCoordinatorMultipleTimes() {
        assertTrue(admin.isHeadCoordinator());
        admin.setHeadCoordinator(false);
        assertFalse(admin.isHeadCoordinator());
        admin.setHeadCoordinator(true);
        assertTrue(admin.isHeadCoordinator());
        admin.setHeadCoordinator(false);
        assertFalse(admin.isHeadCoordinator());
    }
}
